import { cp, readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { renderAdapters } from "./adapters.js";
import { CapabilityRecord, UpdateProposal } from "./types.js";
import { ensureDir, nowIso, pathKind, slugify, stableId } from "./utils.js";
import { paths, readCapabilityRegistry, writeCapabilityRegistry, writeProposal } from "./store.js";

export async function importLocalSkill(root: string, sourcePath: string, input: { status?: CapabilityRecord["status"]; render?: boolean } = {}): Promise<{ capability: CapabilityRecord; installedPath: string; rendered: string[] }> {
  const absoluteSource = path.isAbsolute(sourcePath) ? sourcePath : path.resolve(process.cwd(), sourcePath);
  const kind = await pathKind(absoluteSource);
  if (kind === "missing") throw new Error(`Skill source does not exist: ${sourcePath}`);

  const skillId = inferSkillId(absoluteSource, kind);
  const destinationDir = path.join(paths(root).skills, skillId);
  await ensureDir(destinationDir);

  if (kind === "directory") {
    await cp(absoluteSource, destinationDir, { recursive: true, force: true });
  } else {
    const content = await readFile(absoluteSource, "utf8");
    await ensureDir(destinationDir);
    await import("node:fs/promises").then(({ writeFile }) => writeFile(path.join(destinationDir, "SKILL.md"), content, "utf8"));
  }

  const registry = await readCapabilityRegistry(root);
  const now = nowIso();
  const capability: CapabilityRecord = {
    id: stableId("cap", absoluteSource),
    type: "skill",
    source: { kind: "local", path: absoluteSource },
    description: `Imported local skill from ${absoluteSource}`,
    permissions: { network: false, filesystem: false, secrets: [] },
    risk: "low",
    status: input.status ?? "installed",
    project_fit: { score: 0.5, reasons: ["Imported manually by user."] },
    adapters: { codex: "available", "claude-code": "available" },
    created_at: now,
    updated_at: now,
  };
  const others = registry.capabilities.filter((item) => item.id !== capability.id);
  await writeCapabilityRegistry(root, [...others, capability]);

  await writeProposal(root, {
    id: stableId("proposal", `${capability.id}:${now}`),
    asset: path.relative(root, path.join(destinationDir, "SKILL.md")),
    operation: "update",
    reason: "Imported external skill should be reviewed and adapted to this project before promotion.",
    evidence: [capability.id],
    risk: "low",
    status: "pending_review",
    patch: "Review this imported skill for project-specific commands, validation steps, and safety constraints.",
    created_at: now,
  });

  const rendered = input.render === false ? [] : await renderAdapters(root);
  return { capability, installedPath: path.relative(root, destinationDir), rendered };
}

export async function listCapabilities(root: string): Promise<CapabilityRecord[]> {
  return (await readCapabilityRegistry(root)).capabilities;
}

export async function discoverClaudeSkills(root: string): Promise<{ discovered: CapabilityRecord[]; proposals: UpdateProposal[] }> {
  const skillsDir = path.join(root, ".claude", "skills");
  const entries = await readdir(skillsDir, { withFileTypes: true }).catch(() => []);
  const registry = await readCapabilityRegistry(root);
  const byId = new Map(registry.capabilities.map((capability) => [capability.id, capability]));
  const discovered: CapabilityRecord[] = [];
  const proposals: UpdateProposal[] = [];
  const now = nowIso();

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name === "agentmind-workflow") continue;
    const skillPath = path.join(skillsDir, entry.name, "SKILL.md");
    if (await pathKind(skillPath) !== "file") continue;
    const content = await readFile(skillPath, "utf8");
    if (content.includes("Generated by AgentMind from `.agent-context/skills/")) continue;
    const capabilityId = stableId("cap", skillPath);
    const existing = byId.get(capabilityId);
    const capability: CapabilityRecord = {
      id: capabilityId,
      type: "skill",
      source: { kind: "local", path: skillPath },
      description: `Discovered Claude Code skill ${entry.name}`,
      permissions: existing?.permissions ?? { network: false, filesystem: false, secrets: [] },
      risk: existing?.risk ?? "medium",
      status: existing?.status ?? "discovered",
      project_fit: existing?.project_fit ?? { score: 0.4, reasons: ["Discovered from .claude/skills. Needs review before canonical promotion."] },
      adapters: { codex: existing?.adapters.codex ?? "unknown", "claude-code": "available" },
      created_at: existing?.created_at ?? now,
      updated_at: now,
    };
    byId.set(capability.id, capability);
    discovered.push(capability);
    proposals.push(await writeProposal(root, {
      id: stableId("proposal", `${capability.id}:discover`),
      asset: path.relative(root, path.join(paths(root).skills, slugify(entry.name), "SKILL.md")),
      operation: "create",
      reason: "Claude Code skill was discovered and may be worth promoting into AgentMind canonical skills for cross-harness use.",
      evidence: [capability.id, path.relative(root, skillPath)],
      risk: capability.risk,
      status: "pending_review",
      patch: `Review ${path.relative(root, skillPath)}. If useful and safe, run: agentmind skill promote ${entry.name}`,
      created_at: now,
    }));
  }

  await writeCapabilityRegistry(root, Array.from(byId.values()).sort((left, right) => left.created_at.localeCompare(right.created_at)));
  return { discovered, proposals };
}

export async function promoteSkill(root: string, idOrSkill: string): Promise<{ capability: CapabilityRecord; installedPath: string; rendered: string[] }> {
  const registry = await readCapabilityRegistry(root);
  const capability = registry.capabilities.find((item) => item.id === idOrSkill || inferSkillIdFromCapability(item) === idOrSkill);
  const sourcePath = capability?.source.path;
  const skillId = slugify(capability ? inferSkillIdFromCapability(capability) : idOrSkill);
  const destinationDir = path.join(paths(root).skills, skillId);
  const destinationSkill = path.join(destinationDir, "SKILL.md");
  await ensureDir(destinationDir);

  if (sourcePath && path.resolve(sourcePath) !== path.resolve(destinationSkill)) {
    const kind = await pathKind(sourcePath);
    if (kind === "directory") await cp(sourcePath, destinationDir, { recursive: true, force: true });
    else if (kind === "file") {
      const content = await readFile(sourcePath, "utf8");
      await import("node:fs/promises").then(({ writeFile }) => writeFile(destinationSkill, content, "utf8"));
    } else if (await pathKind(destinationSkill) !== "file") {
      throw new Error(`Skill source is missing and no canonical skill exists: ${sourcePath}`);
    }
  } else if (await pathKind(destinationSkill) !== "file") {
    throw new Error(`No capability or canonical skill found for: ${idOrSkill}`);
  }

  const now = nowIso();
  const promoted: CapabilityRecord = {
    id: capability?.id ?? stableId("cap", destinationSkill),
    type: "skill",
    source: { kind: "local", path: destinationSkill },
    description: capability?.description ?? `Promoted canonical skill ${skillId}`,
    permissions: capability?.permissions ?? { network: false, filesystem: false, secrets: [] },
    risk: capability?.risk ?? "low",
    status: "promoted",
    project_fit: capability?.project_fit ?? { score: 0.7, reasons: ["Promoted manually into canonical AgentMind skills."] },
    adapters: { codex: "available", "claude-code": "available" },
    created_at: capability?.created_at ?? now,
    updated_at: now,
  };
  await writeCapabilityRegistry(root, [...registry.capabilities.filter((item) => item.id !== promoted.id), promoted]);
  const rendered = await renderAdapters(root);
  return { capability: promoted, installedPath: path.relative(root, destinationDir), rendered };
}

export async function renderProjectSkills(root: string): Promise<{ rendered: string[] }> {
  return { rendered: await renderAdapters(root) };
}

function inferSkillId(target: string, kind: "file" | "directory"): string {
  if (kind === "directory") return slugify(path.basename(target));
  return slugify(path.basename(target) === "SKILL.md" ? path.basename(path.dirname(target)) : path.basename(target, path.extname(target)));
}

function inferSkillIdFromCapability(capability: CapabilityRecord): string {
  const sourcePath = capability.source.path ?? capability.id;
  const base = path.basename(sourcePath);
  return slugify(base === "SKILL.md" ? path.basename(path.dirname(sourcePath)) : path.basename(sourcePath, path.extname(sourcePath)));
}
